# Generated by Django 5.0 on 2023-12-22 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_atividade_detalhes_remove_atividade_pontos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='status',
            field=models.CharField(choices=[('A_receber', 'A receber'), ('Recebido', 'Recebido'), ('Em_andamento', 'Em andamento'), ('Concluido', 'Concluído'), ('Cancelada', 'Cancelada')], default='A_receber', max_length=20),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.campo', verbose_name='Órgão/Empresa'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='numero',
            field=models.CharField(max_length=150, verbose_name='Atribuição'),
        ),
    ]
