# Generated by Django 5.0 on 2023-12-22 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_atividade_status_alter_atividade_campo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='data',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Referência'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='status',
            field=models.CharField(choices=[('A receber', 'A receber'), ('Recebido', 'Recebido'), ('Em andamento', 'Em andamento'), ('Concluído', 'Concluído'), ('Cancelada', 'Cancelada')], default='A receber', max_length=20),
        ),
    ]
