# Generated by Django 5.0 on 2023-12-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_atividadeleitura'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='pdf/')),
            ],
        ),
    ]
