# Generated by Django 5.0 on 2023-12-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_envioarquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='arquivo',
            field=models.FileField(default=1, upload_to='pdf/'),
            preserve_default=False,
        ),
    ]
