# Generated by Django 5.0 on 2023-12-28 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_delete_envioarquivo_alter_atividade_arquivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='comentarios/')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.atividade')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
