# Generated by Django 5.0 on 2023-12-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_campo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='arquivo',
            field=models.FileField(blank=True, upload_to='pdf/', verbose_name='Anexos'),
        ),
    ]
