# Generated by Django 5.0 on 2024-01-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_alter_atividade_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='status',
            field=models.CharField(blank=True, choices=[('A receber', 'A receber'), ('Recebido', 'Recebido'), ('Em andamento', 'Em andamento'), ('Concluído', 'Concluído'), ('Cancelada', 'Cancelada')], default='A receber', max_length=20),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(blank=True),
        ),
    ]
