# Generated by Django 5.0 on 2024-01-03 00:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_alter_atividade_status_alter_comentario_texto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=150, verbose_name='Chamado Titulo')),
                ('descricao', models.CharField(max_length=250, verbose_name='Descrição')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data de Referência')),
                ('nivel', models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('MÉDIA', 'MÉDIA'), ('ALTA', 'ALTA')], default='Nivel de Prioridade', max_length=20)),
                ('status', models.CharField(blank=True, choices=[('A receber', 'A receber'), ('Recebido', 'Recebido'), ('Em andamento', 'Em andamento'), ('Concluído', 'Concluído'), ('Cancelada', 'Cancelada')], default='A receber', max_length=20)),
                ('arquivo', models.FileField(blank=True, upload_to='pdf/', verbose_name='Anexos')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.campo', verbose_name='Órgão/Empresa')),
                ('colaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Atribuir')),
            ],
        ),
        migrations.CreateModel(
            name='ChamadoLeitura',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cadastros.chamado',),
        ),
        migrations.CreateModel(
            name='ChamadoComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='comentarios/')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.chamado')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
