# Generated by Django 5.0 on 2024-01-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_chamado_chamadoleitura_chamadocomentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='campo',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='colaborador',
        ),
        migrations.RemoveField(
            model_name='chamadocomentario',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='chamadocomentario',
            name='autor',
        ),
        migrations.DeleteModel(
            name='ChamadoLeitura',
        ),
        migrations.DeleteModel(
            name='Chamado',
        ),
        migrations.DeleteModel(
            name='ChamadoComentario',
        ),
    ]
