# Generated by Django 5.0 on 2024-01-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_remove_chamado_campo_remove_chamado_colaborador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
