# Generated by Django 5.0 on 2024-01-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_alter_atividade_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='agenteCI',
            field=models.CharField(blank=True, max_length=150, verbose_name='Controle Interno'),
        ),
        migrations.AddField(
            model_name='campo',
            name='agenteCPL',
            field=models.CharField(blank=True, max_length=150, verbose_name='CPL'),
        ),
        migrations.AddField(
            model_name='campo',
            name='agenteContabilidade',
            field=models.CharField(blank=True, max_length=150, verbose_name='Contabilidade'),
        ),
        migrations.AddField(
            model_name='campo',
            name='agenteParecer',
            field=models.CharField(blank=True, max_length=150, verbose_name='Jurídico'),
        ),
        migrations.AddField(
            model_name='campo',
            name='agenteSolicita',
            field=models.CharField(blank=True, max_length=150, verbose_name='Solicitação'),
        ),
        migrations.AddField(
            model_name='campo',
            name='gestor1',
            field=models.CharField(blank=True, max_length=150, verbose_name='Gestor Municipal'),
        ),
        migrations.AddField(
            model_name='campo',
            name='gestor2',
            field=models.CharField(blank=True, max_length=150, verbose_name='Gestor FMS'),
        ),
        migrations.AddField(
            model_name='campo',
            name='gestor3',
            field=models.CharField(blank=True, max_length=150, verbose_name='Gestor FMAS'),
        ),
        migrations.AddField(
            model_name='campo',
            name='gestor4',
            field=models.CharField(blank=True, max_length=150, verbose_name='Gestor FMMA'),
        ),
        migrations.AddField(
            model_name='campo',
            name='prefpresi',
            field=models.CharField(blank=True, max_length=150, verbose_name='Presidente/Prefeito'),
        ),
    ]
