# Generated by Django 5.0 on 2023-12-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_perfil_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.FileField(upload_to='imagens/'),
        ),
    ]
